### ISSUE TITLE
Text too much left-aligned

### ISSUE THREAD

**Issue by blumenschwein** [PKM-er/Blue-Topaz_Obsidian-css#601]
The text inside and outside the callout boxes are aligned too much to the left. This happens only with Blue Topaz. With other themes (such as Default), there is no such problem.

Examples:

When using callout, the text inside the color box is aligned too much to the left border:

![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/39619298/06faee0a-0ce0-415f-8f5a-a960f99ab551)

This happens to text both **inside** and **outside** the callout box:

![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/39619298/bdadb0d3-64ae-431e-b828-745f78e81e24)

Also the old-style admonitions have the same problem:

![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/39619298/04f3e069-c5af-4ccb-8ed6-a7731f88fa8f)

On the other hand, the plain code block does not have this problem, i.e., there is more space between text and border of the box:

![image](https://github.com/PKM-er/Blue-Topaz_Obsidian-css/assets/39619298/70e25f6e-a67a-4a9c-ba57-a02a3b3dd7e6)

***
[edit]

Solved by using following css settings:

```css
/* Adjusting padding inside the admonition box */
.admonition-content {
    padding-left: 20px; /* Adjust the padding value as needed */
}

/* Adjusting padding inside the callout box */
.callout-content {
    padding-left: 30px; /* Adjust only the left padding if desired */
}

.callout.callout[data-callout="timeline"] .callout-content blockquote p{
    padding-left: 1em;
    //text-align: center; /* Centralize text */
}

.callout.callout:is([data-callout-metadata*="left"],
[data-callout*=left]) {
  float: left !important;
  margin-right: 40px;
}

.callout.callout:is([data-callout-metadata*="right"],
[data-callout*=right]) {
  float: right !important;
  margin-left: 20px;
}
```
