### ISSUE TITLE
最新版，引用块有奇奇怪怪的空格

### ISSUE THREAD

**Issue by calmwaves111** [PKM-er/Blue-Topaz_Obsidian-css#612]
![image](https://github.com/user-attachments/assets/4681a3d7-ec9b-43a3-ae64-1a484cbc363d)

bt2024071502
没更新前是没这个问题的

**Comment by calmwaves111** [comment]
![image](https://github.com/user-attachments/assets/379d58bb-4958-4350-b73f-173c6665acea)

**Comment by facingbattle** [comment]
直接贴下代码重置代码
这个功能体感很差, 写文章的时候, 抖来抖去的

```css
.cm-active.HyperMD-quote.cm-line:not(.HyperMD-callout) .cm-quote {
    margin-left: 0 !important;
}
```
