### ISSUE TITLE
Dataview list显示会向左偏移1em

### ISSUE THREAD

**Issue by chencyan21** [PKM-er/Blue-Topaz_Obsidian-css#646]
在css文件中，有如下代码：
```css
ul.dataview.list-view-ul>li:not(.task-list-item) {
  border-left: none !important;
  margin-left: -1em;
}
```
这会导致dataview中的list向左边偏移：
```dataviewjs
dv.list(dv.pages('').sort(f=>f.file.mtime.ts,"desc").limit(5).file.link)
```
![Snipaste_2024-12-13_15-13-13](https://github.com/user-attachments/assets/6181bba6-8bbc-4347-9a6a-256ad9330cd5)

删除margin-left属性便会恢复正常
